### ISSUE TITLE
Hi，this is a great work！I want to know when the code will be release？

### ISSUE THREAD

**Issue by Caroline-6** [chunmeifeng/SPRC#1]

**Comment by chunmeifeng** [comment]
> _No description provided._

Thanks for your interest! Will release the code after the CVPR ddl, very busy recently. I will message you when I am ready.

**Comment by Code-kunkun** [comment]
+1

**Comment by baiyang4** [comment]
The training code is released. the checkpoints is in progress and will be released soon

**Comment by lz75258** [comment]
waiting +1

**Comment by hmd78** [comment]
> The training code is released. the checkpoints is in progress and will be released soon

Hi,
thanks for your great work.

I wonder when pretrained checkpoints and finetuned ones ( both for CIRR and FashionIQ ) are going to be released

**Comment by baiyang4** [comment]
> > The training code is released. the checkpoints is in progress and will be released soon
> 
> Hi, thanks for your great work.
> 
> I wonder when pretrained checkpoints and finetuned ones ( both for CIRR and FashionIQ ) are going to be released

Hi, thanks for your interest.
The link for pre-trained weights is now provided in README
