### ISSUE TITLE
Extracting intermediate text representations

### ISSUE THREAD

**Issue by gyglim** [chunmeifeng/SPRC#3]
Hi

Thanks a lot for sharing the code of this strong work.
I am trying to use it to extract explicit text descriptions as shown in Figure 1(c), but struggle to do so.
Here, there is just a hidden representation extracted, rather than text/tokens:
https://github.com/chunmeifeng/SPRC/blob/74b15ab2b00892ec188d1e59151b7730c4599e63/src/lavis/models/blip2_models/blip2_qformer_cir_align_prompt.py#L341

Can you please tell me how to extract these image descriptions / point me to the right direction?

Many thanks in advance

**Comment by baiyang4** [comment]
Hi there, 

Thanks for your interest. The sentence-level prompts in SPRC are implicit word embeddings rather than explicit words(Figure 1(c) is just for demonstration of the sentence-level prompts’ capibility); hence, SPRC cannot explicitly generate real text descriptions to enrich the dataset。
