### ISSUE TITLE
run on one RTX3090 with 24GB memory

### ISSUE THREAD

**Issue by zhw0516** [chunmeifeng/SPRC#5]
Thanks for the great work on the proposed model in advance！
How can the project run on one RTX3090 with 24GB memory?

**Comment by baiyang4** [comment]
Thank you for expressing interest in our work. I suggest experimenting with reducing the batch size and adjusting the learning rate accordingly (usually, a smaller learning rate if you reduce the batch size). With some experimentation, I believe you may achieve similar results.

**Comment by zhw0516** [comment]
Thanks for your reply!
This is not a problem at the training level, but at the validation level, for example, "Compute FashionIQ {relative_val_dataset.dress_types} validation predictions", I noticed that the graphic memory was getting bigger and bigger until cuda out of memory, I wanted to know if there was a solution? Looking forward to your reply.

**Comment by baiyang4** [comment]
I've faced a similar problem with F-IQ, which has three distinct categories. After applying the 'extract_index_blip_features' function, an excessive number of tensors cluttered the GPU memory. To address this, I opted to shift the extracted features to the CPU immediately post-extraction, reserving the GPU for model inference. I wrote the necessary code for this before, will update these code later

**Comment by zhw0516** [comment]
Thank you for your patient reply, looking forward to your new code! Thank you again for the author's excellent work!

**Comment by baiyang4** [comment]
I've updated the code, you can add `--save-memory` in f-iq training command to save memory.

**Comment by zhw0516** [comment]
Thank you very much!
